### ISSUE TITLE
Show hotstring hints only if certain apps are active

### ISSUE THREAD

**Issue by megabugman** [henrystern/hotstring_hints#2]
Please add an option to whitelist apps, where the script will only work if the application is active. for instance I want the script to work only in Outlook and Noteplus++

Cheers

**Comment by henrystern** [comment]
Thanks for the suggestion.

I've added the option by changing the "ignored_applications" setting to "filtered_applications" and adding a new "filter_type" setting which can be set to "whitelist".

Then all you have to do is find the window names of your editors with Window Spy and list them under filtered applications.

For example:
```
filtered_applications=ahk_exe Code.exe, ahk_exe notepad.exe
filter_type=whitelist
```

Best,
Henry
