### ISSUE TITLE
end_char comment gets expanded

### ISSUE THREAD

**Issue by megabugman** [henrystern/hotstring_hints#3]
I added a comment to the settings.ini file. when expanding the hotstring the comment is added:

![bug](https://github.com/henrystern/hotstring_hints/assets/17204819/15c3ea56-e0ac-45e6-97b2-c37c2b4b4fd1)

**Comment by henrystern** [comment]
Unfortunately .ini files don't support trailing comments. 

You can read more [here](https://stackoverflow.com/questions/1378219/do-standard-windows-ini-files-allow-comments).

I would suggest moving the comment to the line above.
